[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.raspi3]
workspace = false
command = "cargo"
args = ["build", "--bin", "raspi", "--target", "aarch64-unknown-none"]