[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[env.release]
BUILD_TYPE = "release"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.raspi3]
workspace = false
script = '''
mkdir -p out
cargo objcopy --bin raspi --target aarch64-unknown-none --features raspi3 -- -O binary out/kernel8.img
'''

[tasks.raspi4]
workspace = false
script = '''
mkdir -p out
cargo objcopy --bin raspi --target aarch64-unknown-none --features raspi4 -- -O binary out/kernel8.img
'''

[tasks.raspi3-qemu]
workspace = false
dependencies = ["raspi3"]
script = '''
qemu-system-aarch64 -serial stdio -M raspi3b -kernel out/kernel8.img
'''

[tasks.raspi4-qemu]
workspace = false
dependencies = ["raspi4"]
script = '''
${QEMU_PATH}/qemu-system-aarch64 -serial stdio -M raspi4b -kernel out/kernel8.img
'''