[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[env.release]
BUILD_TYPE = "release"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.raspi3]
workspace = false
script = '''
cargo build --bin raspi --target aarch64-unknown-none --features raspi3
'''

[tasks.raspi4]
workspace = false
script = '''
cargo build --bin raspi --target aarch64-unknown-none --features raspi4
'''

[tasks.raspi3-qemu]
workspace = false
script = '''
cargo run --bin raspi --target aarch64-unknown-none --features raspi3 -- raspi3
'''

[tasks.raspi3-test]
workspace = false
script = '''
cargo test --package raspi --target aarch64-unknown-none --features raspi3 -- raspi3
'''

[tasks.raspi4-qemu]
workspace = false
script = '''
cargo run --bin raspi --target aarch64-unknown-none --features raspi4 -- raspi4
'''

[tasks.raspi4-test]
workspace = false
script = '''
cargo test --package raspi --target aarch64-unknown-none --features raspi4 -- raspi4
'''