[package]
name = "raspi"
version = "0.1.0"
edition = "2021"

[features]
raspi3 = []
raspi4 = []

[dependencies]
kernel = { path = "../../kernel" }
tock-registers = "0.9.0"

[dependencies.fdt-rs]
version = "0.4.5"
default-features = false
